# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: integration-tests

on:
  push:
    branches: [ "main", "feature/db-integration" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-bookworm
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov alembic
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run migrations
      env:
        DATABASE_URL: postgresql://test:test@localhost:5432/test_db
      run: alembic upgrade head

    - name: Integration tests with pytest
      run: |
        mkdir -p logs
        LOGFILE="logs/pytest-$(date +'%Y-%m-%d_%H%M%S').log"
        pytest -v --tb=long --cov \
        --log-format="%(asctime)s %(levelname)s %(message)s" \
        --log-date-format="%Y-%m-%d %H:%M:%S" \
        --log-file="$LOGFILE" \
        --junitxml=logs/junit.xml
        
    - name: Log reports
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
        name: pytest logs
        # A file, directory or wildcard pattern that describes what to upload
        path: logs/
